service: Demo
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-northeast-1
  logRetentionInDays: 30
  environment:
    STAGE: ${self:provider.stage}
    LOG_LEVEL: INFO

package:
  patterns:
    - "!**/__pycache__"
    - "!**/.mypy_cache"

functions:
  hello:
    handler: src/hello.handler
    environment:
      POWERTOOLS_SERVICE_NAME: DemoHelloFunction

custom:
  alerts:
    alarms:
      - functionErrors
      - functionInvocations
  localstack:
    stages:
      - dev
    host: http://localhost
    edgePort: 4566
    autostart: false
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-localstack
  - serverless-plugin-aws-alerts
  - serverless-prune-plugin
